name: "Compile extension"

on:
  pull_request:
    branches: ["master", "workflows"]
  push:
    branches: ["workflows"]


permissions: 
  contents: read

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: seanmiddleditch/gha-setup-ninja@master
      - uses: microsoft/setup-msbuild@v2
      - run: python -m pip install meson
      - uses: ikalnytskyi/action-setup-postgres@v7
      - run: |
          "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat" && meson setup builddir && meson compile -C builddir
        shell: cmd

    
