name: "Release extension"

on:
  push:
    branches: ["master"]

permissions: 
  contents: read

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: seanmiddleditch/gha-setup-ninja@master
      - uses: microsoft/setup-msbuild@v2
      - run: python -m pip install meson
      - uses: ikalnytskyi/action-setup-postgres@v7
      - run: |
          "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat" && meson setup builddir && meson compile -C builddir
        shell: cmd
      - run: "mkdir scripts"
      - run: "Copy-Item -Path *.py -Destination scripts"
      - run: "Compress-Archive -Path scripts, database_data_generator--1.0.sql, database_data_generator.control, builddir\\database_data_generator.dll -DestinationPath release.zip"
      - uses: actions/create-release@v1
        id: "create_release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: Release ${{ github.sha }}
          draft: false
          prerelease: false
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release.zip
          asset_name: release.zip
          asset_content_type: application/zip

    
